services:
  db:
    image: mariadb:11.4.4
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 8

  web:
    build: .
    image: kouden_summary
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  mariadb_data:
