services:
  db:
    image: mariadb:11.4.4
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    command: >
      sh -c "
      echo 'Waiting for MariaDB to be ready...' &&
      sleep 10 &&
      mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD demo_db -e 'ALTER TABLE sessions MODIFY data MEDIUMBLOB;' &&
      echo 'MEDIUMBLOB applied'
      "
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file:
      - .env.prod-local
    depends_on:
      db:
        condition: service_healthy

volumes:
  mariadb_data:
