FROM python:3.13-slim-bookworm
WORKDIR /app
RUN apt-get update && apt-get install -y bash curl nano
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/
ENV FLASK_DEBUG=1
CMD ["flask", "run"]
