FROM python:3.13-slim-bookworm
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash curl nano mariadb-client git \
    build-essential libssl-dev libffi-dev \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/root/.cargo/bin:${PATH}"
COPY requirements-test.txt /app/
RUN pip install --no-cache-dir -r requirements-test.txt
COPY . /app
COPY entrypoint.test.sh /entrypoint.test.sh
RUN chmod +x /entrypoint.test.sh
ENV FLASK_APP="app:create_app()"
ENV FLASK_DEBUG=1
EXPOSE 5000
ENTRYPOINT ["/entrypoint.test.sh"]
