version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:626635405187:task-definition/flask-task:9"
        LoadBalancerInfo:
          ContainerName: "flask-web"
          ContainerPort: 5000
