"""Add created_at and updated_at timestamps

Revision ID: 80cf81f79c2e
Revises: a7c5f4a71fc8
Create Date: 2025-03-17 00:51:54.227685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80cf81f79c2e'
down_revision = 'a7c5f4a71fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.alter_column('user_cognito_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('user_cognito_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
