"""Auto migration from entrypoint

Revision ID: a7c5f4a71fc8
Revises: a271a7a98622
Create Date: 2025-03-16 01:26:50.556609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7c5f4a71fc8'
down_revision = 'a271a7a98622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.alter_column('tel',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('user_cognito_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_index('ix_summaries_user_cognito_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index('ix_summaries_user_cognito_id', ['user_cognito_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('user_cognito_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('tel',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
