name: CI

on:
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test container
        run: docker build -f Dockerfile.test -t kouden-summary-lint .

      - name: Run ruff lint check
        run: docker run --rm kouden-summary-lint
