name: Terraform CD

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Detect Changed Directories
        id: detect
        run: |
          CHANGED_DIR=$(git diff --name-only HEAD^ HEAD | grep '^terraform/' | cut -d/ -f2 | sort -u | head -n 1)

          if [ -n "$CHANGED_DIR" ]; then
            echo "dir=terraform/$CHANGED_DIR" >> $GITHUB_OUTPUT
            echo "Target directory detected: terraform/$CHANGED_DIR"
          else
            echo "dir=" >> $GITHUB_OUTPUT
            echo "No terraform directory changes detected."
          fi

      - name: Terraform Init
        if: steps.detect.outputs.dir != '' && steps.detect.outputs.dir != 'terraform/'
        run: terraform init
        working-directory: ${{ steps.detect.outputs.dir }}

      - name: Terraform Apply
        if: steps.detect.outputs.dir != '' && steps.detect.outputs.dir != 'terraform/'
        run: terraform apply -auto-approve
        working-directory: ${{ steps.detect.outputs.dir }}
